public class PriortyDemo {

    /** Every thread has a priority, it can be default priority generated by JVM
     *  or custom priority by the programmer
     *
     *  The range of priority is 1 to 10
     *
     *  1 is the lowest priority
     *  10 is the highest priority
     *
     * Thread.MIN_PRIORITY = 1
     * Thread.NORM_PRIORITY = 5
     * Thread.MAX_PRIORITY = 10
     *
     *
     *
     *
     */

    public static void main(String[] args) {

    }

}
